// Copyright 2016 The Iskip Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifdef __GET_T2_STR
#undef __GET_T2_STR
unsigned __insn_t2_str[] = {
  ARM::t2STRBT,
  ARM::t2STRB_POST,
  ARM::t2STRB_PRE,
  ARM::t2STRB_preidx,
  ARM::t2STRBi12,
  ARM::t2STRBi8,
  ARM::t2STRBs,
  ARM::t2STRD_POST,
  ARM::t2STRD_PRE,
  ARM::t2STRDi8,
  ARM::t2STREX,
  ARM::t2STREXB,
  ARM::t2STREXD,
  ARM::t2STREXH,
  ARM::t2STRHT,
  ARM::t2STRH_POST,
  ARM::t2STRH_PRE,
  ARM::t2STRH_preidx,
  ARM::t2STRHi12,
  ARM::t2STRHi8,
  ARM::t2STRHs,
  ARM::t2STRT,
  ARM::t2STR_POST,
  ARM::t2STR_PRE,
  ARM::t2STR_preidx,
  ARM::t2STRi12,
  ARM::t2STRi8,
  ARM::t2STRs,
};
#endif
